server:
  port: 8085
  servlet:
    context-path: /oraclecloud
spring:
  application:
    name: oraclecloud
  datasource:
    url: jdbc:oracle:thin:@t05microservicios_medium?TNS_ADMIN=wallets/Wallet_T05MICROSERVICIOS
    username: atptraductor
    password: Jonathan4041
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true

oracle:
  jdbc:
    fanEnabled: false